#!/usr/bin/env bash

set -euo pipefail

# Mark the necessary Go modules as private to avoid Go's proxy
export GOPRIVATE="${GOPRIVATE:+$GOPRIVATE,}github.com/Metronome-Industries/metronome-go,github.com/stainless-sdks/metronome-go"

go build -o terraform-provider-metronome
