#!/usr/bin/env bash

set -euo pipefail

# Mark the necessary Go modules as private to avoid Go's proxy
export GOPRIVATE="${GOPRIVATE:+$GOPRIVATE,}github.com/Metronome-Industries/metronome-go/v3,github.com/Metronome-Industries/metronome-go-staging/v3"

go build -o terraform-provider-metronome
