#!/usr/bin/env bash

set -euo pipefail

cd "$(dirname "$0")/.."

# Mark the necessary Go modules as private to avoid Go's proxy
export GOPRIVATE="${GOPRIVATE:+$GOPRIVATE,}github.com/Metronome-Industries/metronome-go/v3,github.com/stainless-sdks/metronome-go/v3"

REPLACEMENT="${1:-"../metronome-go"}"
echo "==> Replacing Go SDK with $REPLACEMENT"
go mod edit -replace github.com/Metronome-Industries/metronome-go/v3="$REPLACEMENT"
go mod tidy -e
